networks:
  microservices-net:
    driver: overlay

volumes:
  mysql-usuarios-data:
  mysql-vehiculos-data:
  mysql-contratos-data:
  mysql-ventas-data:
  mongo-vehiculos-data:

services:
  #################
  # MICROSERVICIOS
  #################

  usuarios-ms:
    image: usuarios-ms:latest
    depends_on:
      - usuarios-db
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s

  vehiculos-queries-ms:
    image: vehiculos-queries-ms:latest
    depends_on:
      - vehiculos-queries-db
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s

  vehiculos-commands-ms:
    image: vehiculos-commands-ms:latest
    environment:
      DB_HOST: vehiculos-commands-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: vehiculosdbauto_write
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - vehiculos-commands-db
      - kafka
      - kafka-connect
      - init-connectors
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s

  contratos-ms:
    image: contratos-ms:latest
    depends_on:
      - contratos-db
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s

  ventas-ms:
    image: ventas-ms:latest
    depends_on:
      - ventas-db
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s

  automarketweb:
    image: automarketweb:latest
    ports:
      - "80:80"
    depends_on:
      - kong
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      placement:
        max_replicas_per_node: 1

  kong:
    image: kong:3.7
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_ADMIN_LISTEN: "off"
      KONG_LOG_LEVEL: info
    volumes:
      - ./kong-config:/etc/kong
    depends_on:
      - usuarios-ms
      - vehiculos-queries-ms
      - vehiculos-commands-ms
      - contratos-ms
      - ventas-ms
    networks:
      - microservices-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
      placement:
        max_replicas_per_node: 2

  #####################
  # BASES DE DATOS
  #####################

  usuarios-db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices-net
    volumes:
      - mysql-usuarios-data:/var/lib/mysql
      - ./UsuariosMsAuto/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  vehiculos-queries-db:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_DATABASE: vehiculosdbauto_read
    networks:
      - microservices-net
    volumes:
      - mongo-vehiculos-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  vehiculos-commands-db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SECURE_FILE_PRIV: ""
    command:
      - --secure-file-priv=/tmp/
      - --server-id=223344
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --gtid-mode=ON
      - --enforce-gtid-consistency=TRUE
    networks:
      - microservices-net
    volumes:
      - mysql-vehiculos-data:/var/lib/mysql
      - ./VehiculosMsAuto_Commands/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  contratos-db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices-net
    volumes:
      - mysql-contratos-data:/var/lib/mysql
      - ./ContratosMsAuto/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  ventas-db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices-net
    volumes:
      - mysql-ventas-data:/var/lib/mysql
      - ./VentasMsAuto/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  ################################
  # Kafka, Zookeeper y utilidades
  ################################

  zookeeper:
    image: confluentinc/cp-zookeeper:latest-ubi8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  kafka:
    image: confluentinc/cp-kafka:latest-ubi8
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  kafka-connect:
    image: debezium/connect:2.7.3.Final
    environment:
      GROUP_ID: 1
      ADVERTISED_HOST_NAME: kafka-connect
      BOOTSTRAP_SERVERS: kafka:29092
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: "/kafka/connect,/opt/kafka/plugins"
    volumes:
      - ./VehiculosMsAuto_Queries/kafka-connect:/opt/kafka/plugins
    depends_on:
      - kafka
      - zookeeper
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: vehiculos-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: vehiculos-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_UI_AUTH_USERNAME: "automarket"
      KAFKA_UI_AUTH_PASSWORD: "admin"
    depends_on:
      - kafka
      - kafka-connect
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      placement:
        max_replicas_per_node: 1

  init-kafka-connectors:
    image: curlimages/curl
    depends_on:
      - vehculos-queries-db
      - vehiculos-commands-db
      - kafka-connect
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "echo 'Esperando a Kafka Connect...' &&
       until curl -s http://kafka-connect:8083/connectors; do sleep 5; done &&
       sleep 15 &&
       echo 'Registrando conector MySQL...' &&
       curl -s -o /dev/null -w '%{http_code}' -X POST -H 'Content-Type: application/json' --data @/opt/kafka/configs/mysql-connector.json http://kafka-connect:8083/connectors &&
       echo 'Registrando conector Mongo Sink...' &&
       curl -s -o /dev/null -w '%{http_code}' -X POST -H 'Content-Type: application/json' --data @/opt/kafka/configs/mongo-sink-connector.json http://kafka-connect:8083/connectors"
    volumes:
      - ./VehiculosMsAuto_Queries/kafka-connect:/opt/kafka/configs
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5

  kafka-streams:
    image: kafkastreams-ms:latest
    depends_on:
      - kafka
    networks:
      - microservices-net
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
